# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170728_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='time_of_service',
            new_name='end_time_of_service',
        ),
        migrations.AddField(
            model_name='soldier',
            name='orgins',
            field=models.CharField(default='america', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier',
            name='position',
            field=models.CharField(default='america', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier',
            name='rank',
            field=models.CharField(default='america', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier',
            name='start_time_of_service',
            field=models.DateField(default=-23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier',
            name='theather_of_operation',
            field=models.CharField(default='Africa', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soldier',
            name='branch_of_military',
            field=models.CharField(max_length=20),
        ),
    ]
