# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170731_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='theather_of_operation',
            new_name='theater_of_operations',
        ),
        migrations.RenameField(
            model_name='soldier',
            old_name='start_time_of_service',
            new_name='time_of_service_start',
        ),
    ]
