# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170731_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='time_of_service_start',
        ),
        migrations.AddField(
            model_name='soldier',
            name='time_of_service_s',
            field=models.DateField(default=0.005491990846681922),
            preserve_default=False,
        ),
    ]
